Kopay\NotificationBundle\Entity\Notification:
    type: entity
    table: null
    repositoryClass: Kopay\NotificationBundle\Repository\NotificationRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr_type
        type: string
    discriminatorMap:
        email: NotificationEmail
        push: NotificationPush
    id:
        id:
            type: guid
            id: true
    fields:
        title:
            type: string
            length: 255
            nullable: true
        message:
            type: text
            nullable: true
        createdAt:
            type: datetime
        visible:
            type: boolean
        seenAt:
            type: datetime
            nullable: true
    oneToMany:
        recipientsItems:
            targetEntity: Kopay\NotificationBundle\Entity\NotificationRecipient
            mappedBy: notification
            cascade: ['persist', 'remove']
    lifecycleCallbacks: {  }
