Kopay\NotificationBundle\Entity\NotificationRecipient:
    type: entity
    table: null
    id:
        id:
            type: guid
            id: true
    fields:
        seen:
            type: boolean
    manyToOne:
        notification:
            targetEntity: Kopay\NotificationBundle\Entity\Notification
            inversedBy: recipientsItems
    lifecycleCallbacks: {  }
