Kopay\NotificationBundle\Entity\Notification:
    type: entity
    table: null
    repositoryClass: Kopay\NotificationBundle\Repository\NotificationRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr_type
        type: string
    discriminatorMap:
        email: NotificationEmail
        push: NotificationPush
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true
        message:
            type: text
            nullable: true
        createdAt:
            type: datetime
        seen:
            type: boolean
    lifecycleCallbacks: {  }
