services:
    kopay_notify.listener:
        class: Kopay\NotificationBundle\EventListener\NotificationListener
        arguments:
             - '@doctrine.orm.entity_manager'
             - '@event_dispatcher'
             - '@kopay_notify.job_provider'
             - '@validator'
        tags:
            - { name: kernel.event_listener, event: kopay.notify.message.created, method: onNotificationCreated }

    kopay_notify.sending_provider.email:
        class: Kopay\NotificationBundle\Provider\EmailNotificationProvider
        arguments: ['@mailer']
        tags:
            - {name: kopay_notify.sending_provider, type: email}

    kopay_notify.sending_provider.push:
        class: Kopay\NotificationBundle\Provider\PushNotificationProvider
        tags:
            - {name: kopay_notify.sending_provider, type: push}

    kopay_notify.job_provider:
        class: Kopay\NotificationBundle\Job\JmsJobBundleProvider
        arguments: ['@doctrine.orm.entity_manager']

    kopay_notify.console.send_notification:
        class: Kopay\NotificationBundle\Console\SendNotificationCommand
        arguments: ['@doctrine.orm.entity_manager','@event_dispatcher']
        ## sending providers added in compiler pass
        tags:
            - { name: console.command }

    kopay_notify.metadata_listener:
        class: Kopay\NotificationBundle\EventListener\NotificationMetadataListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    kopay_notify.manager:
        class: Kopay\NotificationBundle\Service\NotificationManager
        arguments: ["%kopay_notify"]