services:
    kopaygorodsky_notification.listener:
        class: Kopay\NotificationBundle\EventListener\NotificationListener
        arguments:
             - '@doctrine.orm.entity_manager'
             - '@event_dispatcher'
             - '@kopaygorodsky_notification.job_provider'
             - '@validator'
        tags:
            - { name: kernel.event_listener, event: kopaygorodsky.notification.message.created, method: onNotificationCreated }

    kopaygorodsky_notification.sending_provider.email:
        class: Kopay\NotificationBundle\Provider\EmailNotificationProvider
        arguments: ['@mailer']
        tags:
            - {name: kopaygorodsky_notifications.sending_provider, type: email, lol: lol}

    kopaygorodsky_notification.sending_provider.push:
        class: Kopay\NotificationBundle\Provider\PushNotificationProvider
        tags:
            - {name: kopaygorodsky_notifications.sending_provider, type: push}

    kopaygorodsky_notification.job_provider:
        class: Kopay\NotificationBundle\Job\JmsJobBundleProvider
        arguments: ['@doctrine.orm.entity_manager']

    kopaygorodsky_notification.console.send_notification:
        class: Kopay\NotificationBundle\Console\SendNotificationCommand
        arguments: ['@doctrine.orm.entity_manager','@event_dispatcher']
        ## sending providers added in compiler pass
        tags:
            - { name: console.command }